### PR TITLE
Add deprecation notice to readme

### LINKED ISSUE #138: Development of this plugin has ended, use the new plugin!
https://github.com/envato/wp-envato-market

### PR DESCRIPTION
**Pull request by jacobbednarz**
There are still users on this version of the wordpress plugin and
even though there is a newer version of the plugin, not everyone knows
that and ends up trying to use this one instead. To make it easy on
people I have just added a notice to the readme as well as a link to the
newer version.

Fixes #138

### CODE REVIEW

**Comment by jacobbednarz** [comment]
cc @valendesigns

**Comment by ejoubaud** [comment]
Thanks @jacobbednarz 👍

**Comment by valendesigns** [comment]
I think the plan is to add the GitHub install script to this plugin so it will install the new plugin with a single click, but are holding out until the new plugin is officially released as v1.0.0. I'll take a look at the PR tomorrow and maybe extend it. The new plugin is stable enough to push it out. I just need to run it by a few people to get the green light.

**Comment by jacobbednarz** [comment]
@valendesigns If possible, I'd ❤️  if we could action something (whether that was a simple notice in the README or an assisted upgrade path) in the near future. We are receiving a handful of tickets around people attempting to use this plugin and it not working as expected and the only advice we can offer is to use the newer plugin. It would be great if we can remove Envato Support as the middle person here and just have the documentation included on the GitHub project page.

**Comment by jacobbednarz** [comment]
any update on this one @valendesigns? we are still receiving tickets about this and I'd like to see us put something in place to get people onto the new version and deter them from using this one.

**Pull request merged**
